# Generated by Django 6.0.6 on 2026-06-07 12:02

import django.db.models.deletion
from django.db import migrations, models


def seed_default_route_catalog(apps, schema_editor):
    ServerLocation = apps.get_model("servers", "ServerLocation")
    Server = apps.get_model("servers", "Server")
    ProductLocation = apps.get_model("routing", "ProductLocation")
    ConnectionRoute = apps.get_model("routing", "ConnectionRoute")

    catalog = (
        {
            "code": "ru",
            "name": "Россия",
            "region": "Europe",
            "country_code": "RU",
            "server_code": "ru-mow-1",
            "server_name": "Russia Moscow 1",
            "provider": "INFINDA Edge",
            "hostname": "ru-mow-1.infinda.local",
            "ip_address": "10.0.0.1",
        },
        {
            "code": "de",
            "name": "Германия",
            "region": "Europe",
            "country_code": "DE",
            "server_code": "de-fra-1",
            "server_name": "Germany Frankfurt 1",
            "provider": "Hetzner",
            "hostname": "de-fra-1.infinda.local",
            "ip_address": "10.0.0.2",
        },
        {
            "code": "nl",
            "name": "Нидерланды",
            "region": "Europe",
            "country_code": "NL",
            "server_code": "nl-ams-1",
            "server_name": "Netherlands Amsterdam 1",
            "provider": "Leaseweb",
            "hostname": "nl-ams-1.infinda.local",
            "ip_address": "10.0.0.3",
        },
        {
            "code": "pl",
            "name": "Польша",
            "region": "Europe",
            "country_code": "PL",
            "server_code": "pl-waw-1",
            "server_name": "Poland Warsaw 1",
            "provider": "OVH",
            "hostname": "pl-waw-1.infinda.local",
            "ip_address": "10.0.0.4",
        },
    )

    for index, item in enumerate(catalog, start=1):
        server_location, _ = ServerLocation.objects.get_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "region": item["region"],
                "country_code": item["country_code"],
            },
        )
        product_location, _ = ProductLocation.objects.get_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "sort_order": index,
                "is_active": True,
            },
        )
        server, _ = Server.objects.get_or_create(
            code=item["server_code"],
            defaults={
                "name": item["server_name"],
                "location": server_location,
                "provider": item["provider"],
                "hostname": item["hostname"],
                "ip_address": item["ip_address"],
                "status": "active",
                "capacity_units": 100,
                "used_capacity_units": 0,
            },
        )
        ConnectionRoute.objects.get_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "location": product_location,
                "server": server,
                "protocol": "outline",
                "endpoint_url": f"https://infinda.com/sub/default/{item['code']}",
                "is_active": True,
                "priority": index,
            },
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Продуктовая локация',
                'verbose_name_plural': 'Продуктовые локации',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConnectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('protocol', models.CharField(default='outline', max_length=32, verbose_name='Протокол')),
                ('endpoint_url', models.URLField(verbose_name='Endpoint URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='servers.server', verbose_name='Сервер')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='routing.productlocation', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Маршрут подключения',
                'verbose_name_plural': 'Маршруты подключения',
                'ordering': ('priority', 'name', 'id'),
            },
        ),
        migrations.RunPython(seed_default_route_catalog, migrations.RunPython.noop),
    ]
