# Generated by Django 6.0.6 on 2026-06-05 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('laptop', 'Laptop')], max_length=16)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=16)),
                ('platform_name', models.CharField(max_length=80)),
                ('client_name', models.CharField(max_length=80)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen', '-created_at'),
            },
        ),
    ]
