# Generated by Django 6.0.6 on 2026-06-05 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('-last_seen', '-created_at'), 'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterField(
            model_name='device',
            name='client_name',
            field=models.CharField(max_length=80, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='device',
            name='icon',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('laptop', 'Laptop')], max_length=16, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='device',
            name='platform_name',
            field=models.CharField(max_length=80, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='device',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отозвано'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
