# Generated by Django 6.0.6 on 2026-06-07 11:48

from django.db import migrations, models


def backfill_device_fields(apps, schema_editor):
    Device = apps.get_model("devices", "Device")

    for device in Device.objects.all().iterator():
        if not device.display_name:
            device.display_name = device.name
        if not device.platform:
            device.platform = device.platform_name
        if not device.client:
            device.client = device.client_name

        if device.revoked_at is not None:
            device.status = "revoked"
        elif device.status == "offline":
            device.status = "stale"
        else:
            device.status = "active"

        device.save(
            update_fields=[
                "display_name",
                "platform",
                "client",
                "status",
                "updated_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_options_alter_device_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='client',
            field=models.CharField(blank=True, max_length=80, verbose_name='Клиент v2'),
        ),
        migrations.AddField(
            model_name='device',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Отображаемое имя'),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(blank=True, max_length=80, verbose_name='Платформа v2'),
        ),
        migrations.AddField(
            model_name='device',
            name='revoked_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина отзыва'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('stale', 'Stale'), ('limit_exceeded', 'Limit exceeded')], max_length=16, verbose_name='Статус'),
        ),
        migrations.RunPython(backfill_device_fields, migrations.RunPython.noop),
    ]
