# Generated by Django 6.0.6 on 2026-06-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_client_device_display_name_device_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='public_device_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Публичный ключ устройства'),
        ),
    ]
