# Generated by Django 6.0.6 on 2026-06-07 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Регион')),
                ('country_code', models.CharField(blank=True, max_length=8, verbose_name='Код страны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Локация сервера',
                'verbose_name_plural': 'Локации серверов',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('provider', models.CharField(max_length=120, verbose_name='Провайдер')),
                ('hostname', models.CharField(max_length=255, verbose_name='Hostname')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='active', max_length=16, verbose_name='Статус')),
                ('capacity_units', models.PositiveIntegerField(default=0, verbose_name='Общая емкость')),
                ('used_capacity_units', models.PositiveIntegerField(default=0, verbose_name='Использовано емкости')),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний heartbeat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='servers.serverlocation', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServerStatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], max_length=16, verbose_name='Статус')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Latency, ms')),
                ('active_connections', models.PositiveIntegerField(default=0, verbose_name='Активных подключений')),
                ('error_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина ошибки')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_snapshots', to='servers.server', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Снимок статуса сервера',
                'verbose_name_plural': 'Снимки статусов серверов',
                'ordering': ('-checked_at', '-id'),
                'indexes': [models.Index(fields=['server', 'checked_at'], name='servers_ser_server__04f086_idx')],
            },
        ),
    ]
