# Generated by Django 6.0.6 on 2026-06-06 10:04

import apps.support.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('closed', 'Закрыт')], default='new', max_length=24, verbose_name='Статус')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
                ('last_message_preview', models.CharField(blank=True, max_length=255, verbose_name='Превью последнего сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыто')),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный администратор')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversation', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Диалог поддержки',
                'verbose_name_plural': 'Диалоги поддержки',
                'ordering': ('-last_message_at', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], max_length=16, verbose_name='Тип отправителя')),
                ('sender_display_name', models.CharField(max_length=255, verbose_name='Имя отправителя')),
                ('source', models.CharField(choices=[('web', 'Web'), ('telegram_support_bot', 'Telegram support bot'), ('admin', 'Admin')], max_length=32, verbose_name='Источник')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportconversation', verbose_name='Диалог')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
            ],
            options={
                'verbose_name': 'Сообщение поддержки',
                'verbose_name_plural': 'Сообщения поддержки',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.support.models.support_attachment_upload_to, verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='MIME-тип')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Размер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportmessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение поддержки',
                'verbose_name_plural': 'Вложения поддержки',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
