# Generated by Django 6.0.6 on 2026-06-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=120, verbose_name='Тариф')),
                ('starts_at', models.DateField(verbose_name='Дата начала')),
                ('ends_at', models.DateField(verbose_name='Активна до')),
                ('max_devices', models.PositiveSmallIntegerField(default=10, verbose_name='Лимит устройств')),
                ('main_url', models.URLField(verbose_name='Основная ссылка подписки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Код страны')),
                ('label', models.CharField(max_length=64, verbose_name='Страна')),
                ('url', models.URLField(verbose_name='Ссылка маршрута')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='subscription.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Маршрут подписки',
                'verbose_name_plural': 'Маршруты подписки',
                'ordering': ('position', 'id'),
                'unique_together': {('subscription', 'code')},
            },
        ),
    ]
