# Generated by Django 6.0.6 on 2026-06-05 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=16, verbose_name='Код тарифа')),
                ('plan_name', models.CharField(max_length=120, verbose_name='Название тарифа')),
                ('amount_rub', models.PositiveIntegerField(verbose_name='Сумма, RUB')),
                ('duration_days', models.PositiveSmallIntegerField(verbose_name='Длительность, дней')),
                ('max_devices', models.PositiveSmallIntegerField(verbose_name='Лимит устройств')),
                ('provider', models.CharField(default='platega', max_length=32, verbose_name='Провайдер')),
                ('payment_method', models.CharField(default='sbp', max_length=32, verbose_name='Метод оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('canceled', 'Отменен'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('external_payment_id', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Внешний ID платежа')),
                ('checkout_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на оплату')),
                ('provider_status', models.CharField(blank=True, max_length=32, verbose_name='Статус провайдера')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload провайдера')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж подписки',
                'verbose_name_plural': 'Платежи подписки',
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_2c9bb5_idx'), models.Index(fields=['provider', 'status'], name='subscriptio_provide_5c0e58_idx')],
            },
        ),
    ]
