# Generated by Django 6.0.6 on 2026-06-07 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('trial_started', 'Триал начат'), ('activated', 'Подписка активирована'), ('renewed', 'Подписка продлена')], max_length=32, verbose_name='Тип события')),
                ('plan_code', models.CharField(blank=True, max_length=16, verbose_name='Код тарифа')),
                ('plan_name', models.CharField(max_length=120, verbose_name='Название тарифа')),
                ('starts_at', models.DateField(verbose_name='Дата начала')),
                ('ends_at', models.DateField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='subscription.subscriptionpayment', verbose_name='Платеж')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='subscription.subscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие подписки',
                'verbose_name_plural': 'События подписки',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
