# Generated by Django 6.0.6 on 2026-06-07 12:02

import django.db.models.deletion
from django.db import migrations, models


def backfill_subscription_route_connection_route(apps, schema_editor):
    SubscriptionRoute = apps.get_model("subscription", "SubscriptionRoute")
    ConnectionRoute = apps.get_model("routing", "ConnectionRoute")

    route_map = {
        route.code: route
        for route in ConnectionRoute.objects.all()
    }

    for subscription_route in SubscriptionRoute.objects.all().iterator():
        connection_route = route_map.get(subscription_route.code)
        if connection_route is None:
            continue

        subscription_route.connection_route = connection_route
        subscription_route.label = connection_route.location.name
        subscription_route.url = connection_route.endpoint_url
        subscription_route.save(update_fields=["connection_route", "label", "url", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
        ('subscription', '0003_subscriptionhistoryevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionroute',
            name='connection_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_routes', to='routing.connectionroute', verbose_name='Управляемый маршрут'),
        ),
        migrations.RunPython(backfill_subscription_route_connection_route, migrations.RunPython.noop),
    ]
