# Generated by Django 6.0.6 on 2026-06-07 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_paid', 'Успешная оплата'), ('subscription_expiring_soon', 'Подписка скоро истекает'), ('device_revoked', 'Устройство отозвано'), ('support_message', 'Новое сообщение поддержки'), ('telegram_linked', 'Telegram привязан'), ('telegram_unlinked', 'Telegram отвязан')], max_length=64, verbose_name='Тип события')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], max_length=32, verbose_name='Канал')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=16, verbose_name='Статус доставки')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ошибка отправки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'event_type'], name='notificatio_user_id_b16834_idx'), models.Index(fields=['channel', 'status'], name='notificatio_channel_289841_idx')],
            },
        ),
    ]
