# Generated by Django 6.0.6 on 2026-06-08 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_client_device_display_name_device_platform_and_more'),
        ('provisioning', '0002_serverprovisioningprofile_panel_base_url_and_more'),
        ('routing', '0001_initial'),
        ('servers', '0001_initial'),
        ('subscription', '0005_subscription_public_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionedDeviceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('error', 'Ошибка'), ('revoked', 'Отозван')], default='active', max_length=16, verbose_name='Статус')),
                ('adapter', models.CharField(blank=True, max_length=16, verbose_name='Адаптер')),
                ('external_client_uuid', models.CharField(blank=True, max_length=64, verbose_name='Внешний UUID клиента')),
                ('external_client_email', models.CharField(blank=True, max_length=190, verbose_name='Внешний email клиента')),
                ('external_client_id', models.CharField(blank=True, max_length=120, verbose_name='Внешний ID клиента')),
                ('inbound_id', models.PositiveIntegerField(default=0, verbose_name='Inbound ID')),
                ('connection_url', models.TextField(blank=True, verbose_name='Ссылка подключения')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('last_error_code', models.CharField(blank=True, max_length=64, verbose_name='Последний код ошибки')),
                ('last_error_message', models.CharField(blank=True, max_length=255, verbose_name='Последняя ошибка')),
                ('provisioned_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдано')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Выданный доступ устройства',
                'verbose_name_plural': 'Выданные доступы устройств',
                'ordering': ('device_id', 'route_id', 'id'),
            },
        ),
        migrations.RenameIndex(
            model_name='provisioningoperation',
            new_name='provisionin_user_id_fc5e28_idx',
            old_name='provisioning_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='provisioningoperation',
            new_name='provisionin_status_c528b9_idx',
            old_name='provisioning_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='provisioningoperation',
            new_name='provisionin_operati_236608_idx',
            old_name='provisioning_type_created_idx',
        ),
        migrations.AddField(
            model_name='provisioneddeviceaccess',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioned_accesses', to='devices.device', verbose_name='Устройство'),
        ),
        migrations.AddField(
            model_name='provisioneddeviceaccess',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioned_accesses', to='routing.connectionroute', verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='provisioneddeviceaccess',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioned_accesses', to='servers.server', verbose_name='Сервер'),
        ),
        migrations.AddField(
            model_name='provisioneddeviceaccess',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisioned_device_accesses', to='subscription.subscription', verbose_name='Подписка'),
        ),
        migrations.AddField(
            model_name='provisioneddeviceaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioned_device_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='provisioneddeviceaccess',
            index=models.Index(fields=['user', 'status'], name='provisionin_user_id_44531d_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioneddeviceaccess',
            index=models.Index(fields=['server', 'status'], name='provisionin_server__f75f74_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioneddeviceaccess',
            index=models.Index(fields=['subscription', 'status'], name='provisionin_subscri_8a4bfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='provisioneddeviceaccess',
            constraint=models.UniqueConstraint(fields=('device', 'route'), name='uniq_provisioned_access_device_route'),
        ),
    ]
